name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

permissions:
  actions: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x setupJdks
#      TODO: enable
#    - name: Publish to OSSRH
#      run: ./gradlew -Pversion=${{ github.event.inputs.version }} publish closeAndReleaseRepository
#      env:
#        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
#        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
#        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
#        ORG_GRADLE_PROJECT_ossrhToken: ${{ secrets.OSSRH_TOKEN }}
    - name: Release
      run: ./gradlew -Pversion=${{ github.event.inputs.version }} setupJdks jreleaserAssemble jreleaserFullRelease
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_DOCKER_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
